# **Exercise 1**

In [ ]:
# 1.1 Import numpy and transform the following list into a NumPy array
a = [10,39,10,20,40,21,55,23,66,76]


In [ ]:
# 1.2 Select all values larger than 20 with boolean indexing


array([39, 40, 21, 55, 23, 66, 76])

In [ ]:
# 1.3 Add the following list of values to a
b = [2,4,5]


[10 39 10 20 40 21 55 23 66 76  2  4  5]


In [ ]:
# 1.4 compute mean and standard deviation of this array


mean 28.53846153846154
std 23.705291147808474


In [ ]:
# 1.5  multiply each value in list a by 2


array([ 9, 38,  9, 19, 39, 20, 54, 22, 65, 75,  1,  3,  4])

# **Exercise 2**

In [ ]:
data = {
        "Name":["Clara", "Tom", "Sarah", "John"],
        "Gender":["F","M","F","M"],
        "Age":[20,25,28,22]
        }

In [ ]:
# 2.1 import pandas and create a dataframe from dictionary data


In [ ]:
# 2.2 Add a new column 'Grade' with the list grades to the dataframe
grades = [2,3,4,1]

In [ ]:
# 2.3 sort the entries of the dataframe by their age


In [ ]:
# 2.4 compute the mean age


In [ ]:
# 2.5 compute the mean age of all female persons


# **Exercise 3**

In [ ]:
data = {
        "Name":["Clara", "Tom", "Sarah"],
        "Gender":["F","M","F"],
        "Age":[20,25,28]
        }


data2 = {
        "Name":["Clara", "Tom", "John"],
        "Subject":["Physics","Politics","English"],
        "Grade":[2,1,3]
        }
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data2)

In [ ]:
# 3.1 merge df1 and df2 on Name, try out left, right joins


In [ ]:
# 3.2 Compute the mean age per gender for df1 with a group-by


## **Exercise 4**

In [ ]:
# Execute this cell to import pandas and load data
import pandas as pd
df = pd.read_csv('https://drive.google.com/uc?id=1Rzq2VqPVRM2kfMuh_jToJKzKUvBOC0vp')

# some cleaning, we come to this topic later
df['price'] = df['price'].str.replace('$','').str.replace(',','').astype(float)

<ipython-input-2-e846cf4fc00d>:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['price'] = df['price'].str.replace('$','').str.replace(',','').astype(float)


In [ ]:
# 4.1 show the head (first 5 rows) of dataframe df

In [ ]:
# 4.2 import matplotlib.pyplot and create a histogram (plt.hist()) from the price column of dataframe df

In [ ]:
# 4.3 add the range parameter to the plt.hist call: plt.hist(...,range=(x_min_value, x_max_value))


In [ ]:
# 4.4 create a scatter plot with plt.scatter(x,y)
# where x is the price column from df and y the square_feet column